#!/bin/bash

chown -R root:wheel /var/jb/Applications/JBDevTestApp.app
chmod +s /var/jb/Applications/JBDevTestApp.app/JBDevTestApp

launchctl stop chaoge.jbdevtest
launchctl load /var/jb/Library/LaunchDaemons/chaoge.jbdevtest.plist
launchctl start chaoge.jbdevtest

uicache -p /var/jb/Applications/JBDevTestApp.app
exit 0

