#!/bin/bash

launchctl stop com.apple.mobile.lockdown
launchctl stop com.apple.mobile.installd
launchctl stop com.apple.streaming_zip_conduit
launchctl start com.apple.mobile.lockdown
launchctl start com.apple.mobile.installd
launchctl start com.apple.streaming_zip_conduit
launchctl stop chaoge.jbdev
launchctl load @@JBROOT@@/Library/LaunchDaemons/chaoge.jbdev.plist
launchctl start chaoge.jbdev
exit 0
