ARCHS=arm64

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = JBDevTestTweak

JBDevTestTweak_FILES = JBDevTestTweak/JBDevTestTweak.x
JBDevTestTweak_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
